# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2018, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3.7\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-04-17 23:44+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: Dong-gweon Oh <flowdas@gmail.com>\n"
"Language-Team: Korean (https://python.flowdas.com)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: ../../library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr "예외"

#: ../../library/asyncio-exceptions.rst:10
msgid "**Source code:** :source:`Lib/asyncio/exceptions.py`"
msgstr "**소스 코드:** :source:`Lib/asyncio/exceptions.py`"

#: ../../library/asyncio-exceptions.rst:16
#, fuzzy
msgid ""
"A deprecated alias of :exc:`TimeoutError`, raised when the operation has "
"exceeded the given deadline."
msgstr "작업이 주어진 마감 시간을 초과했습니다."

#: ../../library/asyncio-exceptions.rst:21
#, fuzzy
msgid "This class was made an alias of :exc:`TimeoutError`."
msgstr ":exc:`RuntimeError`\\의 서브 클래스입니다."

#: ../../library/asyncio-exceptions.rst:26
msgid "The operation has been cancelled."
msgstr "작업이 취소되었습니다."

#: ../../library/asyncio-exceptions.rst:28
msgid ""
"This exception can be caught to perform custom operations when asyncio "
"Tasks are cancelled.  In almost all situations the exception must be re-"
"raised."
msgstr ""
"이 예외는 asyncio 태스크가 취소될 때 사용자 정의 작업을 수행하기 위해 잡을 수 있습니다. 거의 모든 상황에서 예외를 다시 "
"일으켜야 합니다."

#: ../../library/asyncio-exceptions.rst:34
#, fuzzy
msgid ""
":exc:`CancelledError` is now a subclass of :class:`BaseException` rather "
"than :class:`Exception`."
msgstr ":exc:`CancelledError`\\는 이제 :class:`BaseException`\\의 서브 클래스입니다."

#: ../../library/asyncio-exceptions.rst:39
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr ":class:`Task` 나 :class:`Future`\\의 내부 상태가 잘못되었습니다."

#: ../../library/asyncio-exceptions.rst:41
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr "이미 결괏값이 설정된 *Future* 객체에 대해 결괏값을 설정하는 것과 같은 상황에서 발생할 수 있습니다."

#: ../../library/asyncio-exceptions.rst:47
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file "
"type."
msgstr "주어진 소켓이나 파일 유형에서는 \"sendfile\" 시스템 호출을 사용할 수 없습니다."

#: ../../library/asyncio-exceptions.rst:50
msgid "A subclass of :exc:`RuntimeError`."
msgstr ":exc:`RuntimeError`\\의 서브 클래스입니다."

#: ../../library/asyncio-exceptions.rst:55
msgid "The requested read operation did not complete fully."
msgstr "요청한 읽기 작업이 완전히 완료되지 않았습니다."

#: ../../library/asyncio-exceptions.rst:57
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr ":ref:`asyncio 스트림 API <asyncio-streams>`\\가 일으킵니다."

#: ../../library/asyncio-exceptions.rst:59
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr "이 예외는 :exc:`EOFError`\\의 서브 클래스입니다."

#: ../../library/asyncio-exceptions.rst:63
msgid "The total number (:class:`int`) of expected bytes."
msgstr "기대하는 바이트의 총수 (:class:`int`)."

#: ../../library/asyncio-exceptions.rst:67
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr "스트림이 끝나기 전에 읽은 :class:`bytes` 문자열."

#: ../../library/asyncio-exceptions.rst:72
msgid "Reached the buffer size limit while looking for a separator."
msgstr "구분 기호를 찾는 동안 버퍼 크기 제한에 도달했습니다."

#: ../../library/asyncio-exceptions.rst:74
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr ":ref:`asyncio 스트림 API <asyncio-streams>`\\가 일으킵니다."

#: ../../library/asyncio-exceptions.rst:78
msgid "The total number of to be consumed bytes."
msgstr "소비된 바이트의 총수."

#~ msgid ""
#~ "This exception is different from the "
#~ "builtin :exc:`TimeoutError` exception."
#~ msgstr "이 예외는 내장 :exc:`TimeoutError` 예외와 다릅니다."

